### ISSUE TITLE
Hello, thank you for developing such a great package.

### ISSUE THREAD

**Issue by EvoDmiK** [LearningnRunning/NaverTrans#1]
Thank you for developing such a good package.
Thanks to this, it became easier to develop a thesis translator using OCR and translation api that I am developing.

[[my research paper translate test code]](https://github.com/EvoDmiK/TIL/blob/main/AI_study/CV/OCR/pdf2text.ipynb)

p.s. I am not good at English, so I wrote this sentence using navertrans.

**Comment by EvoDmiK** [comment]
논문 번역 프로그램을 개발하며 버그를 하나 발견했는데, 
번역을 두 번 연속할 때 get_response() 함수에서 에러가 납니다.

코드 확인해보니 네이버 번역 서비스 쪽에서 응답으로 에러 메시지를 받을때,아래 이미지 같은 에러가 발생합니다.
![bug report](https://github.com/LearningnRunning/NaverTrans/assets/93193661/20be136d-04f6-4087-91bf-db550338b169)

**Comment by LearningnRunning** [comment]
Thank you for your interest in the Navertrans package. We apologise for the TypeError above. 

In the last 0.0.4 update, we updated it so that you can get translation results even when you enter more than 500 characters. The above error was a case where the error occurred on successive requests. We fixed the error by adding the same arguments to the error message. Thank you.

```
    if 'error' in data['message'] :
        r = get_response(update_token(_agent), text, src_lan, tar_lan)
```

Please update to the fixed version 0.0.5. 

```
pip install --upgrade navertrans
```

**Comment by EvoDmiK** [comment]
thank you for your reply!
have a good day~ 😄

**Comment by EvoDmiK** [comment]
thank you for your reply!
have a good day~ 😄
